#!/usr/bin/env bash

# Check if the script is being run with root privileges
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root."
    exit 1
fi

# Get the directory of the current script
SCRIPT_DIR=$(dirname "$0")

# Set the path to the manage_my_process script
MANAGE_MY_PROCESS_SCRIPT="$SCRIPT_DIR/manage_my_process"

# Check the number of arguments passed to the script
if [[ $# -ne 1 ]]; then
    echo "Usage: $0 {start|stop|restart}"
    exit 1
fi

case $1 in
    start)
        $MANAGE_MY_PROCESS_SCRIPT start
        ;;
    stop)
        $MANAGE_MY_PROCESS_SCRIPT stop
        ;;
    restart)
        $MANAGE_MY_PROCESS_SCRIPT restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
