#!/usr/bin/env bash

function start_process() {
    echo "Starting manage_my_process..."
    ./manage_my_process >> /tmp/my_process 2>&1 &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
}

function stop_process() {
    echo "Stopping manage_my_process..."
    if [[ -f /var/run/my_process.pid ]]; then
        pid=$(cat /var/run/my_process.pid)
        kill "$pid"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

function restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted"
}

function display_usage() {
    echo "Usage: $0 {start|stop|restart}"
}

function write_alive_message() {
    while true; do
        echo "I am alive!" >> /tmp/my_process
        sleep 2
    done
}

case $1 in
    start)
        start_process
        write_alive_message &
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        write_alive_message &
        ;;
    *)
        display_usage
        exit 1
        ;;
esac
